### PR TITLE
Enable Variable and Property creation under variables

### PR DESCRIPTION
**Pull request by w4tsn**
Fixes issue #54.

Based on [this whitepaper](http://www.ascolab.com/images/stories/ascolab/doc/ua_whitepaper_technicaloverview_e.pdf) it should be possible to add Variables and Properties to Variables. Excerpt from the whitepaper:

|Type Definitions|Comment|
|-|-|
|VariableTypes|Data variables (typed) represent data of an object, can be complex (have other data variables) and have properties. Properties (identified by BrowseName) represent characteristics of objects or variables (engineering unit, version number, etc.), there are special services for fast access, properties are leafs of each hierarchy|

### CODE REVIEW

**Comment by oroulet** [comment]
OK. Anyway the point here was just to avoid obvious errors

**Comment by zerox1212** [comment]
With so many type choices I don't really see the point of allowing this and having a variable object have child variables doesn't seem like great design to me. However it doesn't hurt much and have properties under a variable could be useful.

**Comment by oroulet** [comment]
It was just too avoid having people creating new objectypes under root and things like that. Thank you for the pr. Any feedback (or better pr ) is welcome.

**Comment by w4tsn** [comment]
@zerox1212 the latter is my use case, annotating the variables with various meta-data in a huge distributed system of systems comprised of multiple reoccurring components. I added the former just as it satisfies the specification and using or not using it remains, as you say and I agree, a design choice.

**Comment by araisch** [comment]
In my opinion using those predefined Structures is a significant part of the spec. 
```
<UADataType NodeId="i=887" BrowseName="EUInformation">
<DisplayName>EUInformation</DisplayName>
<References>
<Reference ReferenceType="HasSubtype" IsForward="false">i=22</Reference>
</References>
<Definition Name="EUInformation">
<Field Name="NamespaceUri" DataType="i=12"/>
<Field Name="UnitId" DataType="i=6"/>
<Field Name="DisplayName" DataType="i=21"/>
<Field Name="Description" DataType="i=21"/>
</Definition>
</UADataType>
```
Is this somewhere on the agenda already?

**Comment by oroulet** [comment]
There is almost complete support for structures. Look at readme

**Comment by araisch** [comment]
This covers user defined custom structures, as I understand. EUInformation (among others) is a built-in OPC UA structure. Should that work as well? Can't see any fields after creating it.. just a Value with DataType "Null".

**Comment by oroulet** [comment]
If it is built in, it is already available in ua namespace from python or whatever language

**Comment by araisch** [comment]
So I am imcapable to use it, maybe someone can help?
I created a Variable with TypeDefinition "AnalogItemType" from OPCUA Spec:
image
so there should be those properties:
image

In UAModeler it looks like that:
image
and the property "EngineeringUnits" with TypeDef "EUInformation" has the values:
image
How to do that in the OpcUaModeler?

**Comment by oroulet** [comment]
How do you do what? Everything looks correct in my eyes...🤔

**Comment by araisch** [comment]
Sorry was still editing, you're really fast :) 
How do I access the fields of the structure.. 
```
<Definition Name="EUInformation">
<Field Name="NamespaceUri" DataType="i=12"/>
<Field Name="UnitId" DataType="i=6"/>
<Field Name="DisplayName" DataType="i=21"/>
<Field Name="Description" DataType="i=21"/>
</Definition>
```

**Comment by oroulet** [comment]
Dobbel clock on value?

**Comment by araisch** [comment]
It has a "null"-DataType, like marked on the picture above. Clicking on it throws that:
```
uawidgets.utils - ERROR - Datatype must be a subtype of builtin types Node(NumericNodeId(i=887))')
Traceback (most recent call last):
  File "c:\program files (x86)\wpy-3710\python-3.7.1.amd64\lib\site-packages\uawidgets\utils.py", line 21, in wrapper
    result = func(self, *args)
  File "c:\program files (x86)\wpy-3710\python-3.7.1.amd64\lib\site-packages\uawidgets\attrs_widget.py", line 322, in setModelData
    self._set_attribute_data(data, editor, model, idx)
  File "c:\program files (x86)\wpy-3710\python-3.7.1.amd64\lib\site-packages\uawidgets\attrs_widget.py", line 363, in _set_attribute_data
    data.uatype = self.attrs_widget.current_node.get_data_type_as_variant_type()
  File "c:\program files (x86)\wpy-3710\python-3.7.1.amd64\lib\site-packages\opcua\common\node.py", line 99, in get_data_type_as_variant_type
    return opcua.common.ua_utils.data_type_to_variant_type(Node(self.server, result.Value.Value))
  File "c:\program files (x86)\wpy-3710\python-3.7.1.amd64\lib\site-packages\opcua\common\ua_utils.py", line 210, in data_type_to_variant_type
    base = get_base_data_type(dtype_node)
  File "c:\program files (x86)\wpy-3710\python-3.7.1.amd64\lib\site-packages\opcua\common\ua_utils.py", line 234, in get_base_data_type
    raise ua.UaError("Datatype must be a subtype of builtin types {0!s}".format(datatype))
opcua.ua.uaerrors._base.UaError: Datatype must be a subtype of builtin types Node(NumericNodeId(i=887))
```

**Comment by zerox1212** [comment]
I think you are confused. The data type of the node does not have to match the datatype of the value (which is stupid, but I think this has come up before and UA allows it).

Set the value from code instead of the GUI and I bet it will work.

**Pull request merged**
