### PR TITLE
Export instantiated nodes

### PR DESCRIPTION
**Pull request by zerox1212**
When a new node is added, search for it's children recursively and add
them to the export list
Fix name space exports

### CODE REVIEW

**Comment by oroulet** [comment]
instantiate already returns all the children that are instantiated. so I though this was better to use that instead of browsing one more time the address space. I merged this to master but this does not fix all things you had in this PR...sorry it creates a conflict...

**Comment by oroulet** [comment]
ok fixed the namespace stuff too. Thanks for the report

**Comment by zerox1212** [comment]
I will test your way, but I think how I had it looks nicer even if we technically get the children a second time.

Another possible option would be to change `create_object` in manage_nodes.py to return more than node `[0]`.

```python
return instantiate(parent, objecttype, nodeid, qname)[0]
```

**Comment by oroulet** [comment]
I am also afraid of getting children recursively ...Users may create loops in address space and we will hang.... But I agree that avoiding the test for list would be nice

**Comment by zerox1212** [comment]
These items were fixed in other commits. Closing...

**Pull request closed without merging**
